# 1. 다차원 배열

## 1.1 다차원 배열의 연산

* **다차원 배열** : 숫자가 한 줄로 늘어선 것이나 직사각형으로 늘어놓은 것, 3차원으로 늘어놓은 것이나 (더 일반화한) N차원으로 나열하는 것.

In [1]:
import numpy as np
A = np.array([1,2,3,4])
A

array([1, 2, 3, 4])

In [5]:
# 배열의 차원 수
np.ndim(A)

1

In [3]:
# 배열의 형상
A.shape

(4,)

In [4]:
A.shape[0]

4

In [6]:
B = np.array([[1,2],[3,4],[5,6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
np.ndim(B)

2

In [10]:
B.shape

(3, 2)

In [16]:
C = np.array([
    [[1,2,3],[3,4,5],[5,6,7]],
    [[7,8,9],[9,10,11],[11,12,13]]
])
C

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 5,  6,  7]],

       [[ 7,  8,  9],
        [ 9, 10, 11],
        [11, 12, 13]]])

In [17]:
np.ndim(C)

3

In [18]:
C.shape

(2, 3, 3)

## 1.2 행렬의 내적(행렬 곱)

행렬 내적은 왼쪽 행렬의 행(가로)과 오른쪽 행렬의 열(세로)을 원소별로 곱하고 그 값들을 더해서 계산함.

In [23]:
A = np.array([[1,2],[3,4]])
print(A.shape)
B = np.array([[5,6],[7,8]])
print(B.shape)
# 행렬 내적
print(np.dot(A,B))
print(np.dot(B,A))

(2, 2)
(2, 2)
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


내적(scala product, dot product)에서 피연산자의 순서가 다르면 결과도 다름.

In [26]:
A = np.array([[1,2,3],[4,5,6]])
print(A.shape)
B = np.array([[1,2],[3,4],[5,6]])
print(B.shape)
np.dot(A,B)

(2, 3)
(3, 2)


array([[22, 28],
       [49, 64]])

**행렬의 형상에 주의해야 함.**  
첫 번째 행렬의 1번째 차원의 원소 수(열 수)와 두 번째 행렬의 0번째 차원의 원소 수(행 수)가 같아야 함. 두 행렬의 대응하는 차원의 원소 수가 다를 경우 내적 불가.

행렬 C = 행렬 A와 행렬 B의 내적  
행렬 A와 행렬 B의 대응하는 차원의 원소 수가 같아야하고,  
계산 결과인 행렬 C의 형상은 행렬 A의 행 수와 행렬 B의 열 수 가 됨.

## 1.3 신경망의 내적

In [18]:
X = np.array([1,2])
print(X.shape)
W = np.array([[1,3,5], [2,4,6]])
print(W.shape)
Y = np.dot(X,W)
Y

(2,)
(2, 3)


array([ 5, 11, 17])

## 1.4 3층 신경망 구현

신경망에서의 계산을 행렬 계산(내적)으로 정리할 수 있음.

In [2]:
X = np.array([1.0, 0.5])
W = np.array([[0.1, 0.3, 0.5],[0.2,0.4,0.6]])
B1 = np.array([0.1, 0.2, 0.3])

A1 = np.dot(X, W) + B1

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x)) # 브로드캐스트

In [4]:
Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [8]:
W2 = np.array([[0.1,0.4,],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])

A2 = np.dot(Z1,W2) + B2
Z2 = sigmoid(A2)

In [9]:
# 항등함수 f(x) = x
def indentity_function(x):
    return x
W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])

In [10]:
A3 = np.dot(A2, W3) + B3
Y = indentity_function(A3)

출력층의 활성화 함수는 풀고자 하는 문제의 성질에 맞게 정함.  
eg >
* 회귀 -> 항등 함수
* 2클래스 분류 -> 시그모이드 함수
* 다중 클래스 분류 -> 소프트맥스 함수

## 1.5 구현 정리

In [17]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def identity_function(x):
    return x

def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['B1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['B2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
    network['B3'] = np.array([0.1, 0.2])
    
    return network

# 신호가 순방향(입력에서 출력 방향)으로 전달됨(순전파)
def forward(network, x):
    w1, w2, w3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['B1'], network['B2'], network['B3']
    
    a1 = np.dot(x,w1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1,w2)+ b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, w3) + b3
    y = identity_function(a3)
    
    return y
    
    
network = init_network()
x = np.array([1.0,0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]
